FROM maven:3.6.3-jdk-13 AS BUILDER
WORKDIR /tmp
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src /tmp/src/
RUN mvn package

FROM adoptopenjdk/openjdk13:alpine-jre
LABEL maintainer="aime.mathieu1@gmail.com"

COPY --from=BUILDER /tmp/target/*.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
